# ================================================
# TerminSuite - OpenLDAP Container Configuration
# ================================================
# Description:
#   OpenLDAP provides a centralized directory for
#   user and group management within TerminSuite.
# ================================================

name: openldap

services:
  openldap:
    image: bitnami/openldap:latest
    container_name: openldap
    restart: unless-stopped
    secrets:
      - admin_username
      - admin_password
    env_file:
      - openldap.env
    volumes:
      - ./ldif:/ldifs:ro
      - ./data:/bitnami/openldap
    networks:
      - openldap_net

# ------------------------------------------------
# Docker Secret Definition
# ------------------------------------------------
# The file defined here must exist locally before running
# 'docker compose up'. It will be securely mounted inside
# the container at runtime.
# ------------------------------------------------
secrets:
  admin_username:
    file: ./secrets/admin_username.txt
  admin_password:
    file: ./secrets/admin_password.txt

# ------------------------------------------------
# Docker Network Definition
# ------------------------------------------------
networks:
  openldap_net:
    name: openldap_net