# ================================================
# TerminSuite - Internal SSH Bridge for Remote Services
# ================================================
# Description:
#   The container uses a dedicated network connector_net to 
#   isolate SSH tunnels from other networks.
#   
#   SSH credentials are mounted as read-only to prevent accidental 
#   modification or exposure.
#   
#   The service restarts automatically unless manually stopped.
# ================================================

name: connector

services:
  connector:
    container_name: connector
    build: .
    restart: unless-stopped
    volumes:
      - ./ssh:/ssh:ro

# ------------------------------------------------
# Docker Network Definition
# ------------------------------------------------
networks:
  default:
    name: connector_net
