# ==========================================
# TerminSuite — Traefik Site Configuration
# ==========================================
# This file defines the Traefik router and service for Keycloak.
# All traffic is encrypted with Cloudflare-issued certificates
# and forwarded through the connector container to Keycloak.
# ==========================================

http:
  routers:
    keycloak:
      entryPoints:
        - websecure                             # HTTPS entrypoint
      rule: "Host(`keycloak.domain.com`)"           # Replace with your Cloudflare-proxied domain
      service: keycloak
      tls:
        certresolver: cloudflare                # Use Cloudflare certificate resolver

  services:
    keycloak:
      loadBalancer:
        servers:
          - url: "http://connector:12443"             # Internal SSH tunnel port