name: pihole
services:
    pihole:
        container_name: pihole
        image: pihole/pihole:latest
        restart: unless-stopped
        env_file:
            - pihole.env
        secrets:
            - web_password
        ports:
            - 127.0.0.1:18053:53/tcp
            - 127.0.0.1:18053:53/udp
        volumes:
            - './etc-pihole:/etc/pihole'
            - './etc-dnsmasq.d:/etc/dnsmasq.d'
        labels:
            - "traefik.enable=true"

            - "traefik.http.routers.pihole.rule=Host(`pihole.domain.com`)"
            - "traefik.http.routers.pihole.entrypoints=websecure"
            - "traefik.http.routers.pihole.tls.certresolver=cloudflare"
            - "traefik.http.routers.pihole.service=pihole"

            - "traefik.http.services.pihole.loadbalancer.server.port=80"
secrets:
    web_password:
        file: secrets/credentials/web_password.txt
networks:
    default:
        name: pihole_net
