# ============================================================
# TerminSuite - Passbolt Deployment (Docker Compose)
# ============================================================
# Description:
#   Passbolt is an open-source password manager for teams.
#   This setup deploys the Passbolt CE server along with a
#   dedicated MariaDB backend. All sensitive data is handled
#   via Docker Secrets to improve security.
#
# Notes:
#   - The Passbolt container is bound to localhost (127.0.0.1)
#     to ensure access only through Traefik.
#   - Ports and credentials are defined through environment files
#     and secrets for better maintainability.
# ============================================================

name: passbolt

services:
  # ----------------------------------------------------------
  # MariaDB Database Service
  # ----------------------------------------------------------
  passbolt_db:
    container_name: passbolt_db
    image: mariadb:latest
    restart: unless-stopped
    env_file:
      - mariadb.env
    secrets:
      - db_database
      - db_username
      - db_password
    volumes:
      - passbolt_db_vol:/var/lib/mysql
      - ./secrets/passbolt.sql:/docker-entrypoint-initdb.d/dump.sql

  # ----------------------------------------------------------
  # Passbolt Server Service
  # ----------------------------------------------------------
  passbolt_server:
    container_name: passbolt_server
    image: passbolt/passbolt:latest-ce-non-root
    restart: unless-stopped
    depends_on:
      - passbolt_db
    env_file:
      - passbolt.env
    secrets:
      - db_database
      - db_username
      - db_password
      - server_key_public
      - server_key_private
    volumes:
      - passbolt_jwt_vol:/etc/passbolt/jwt
      # Uncomment below if using Passbolt PRO
      # - ./secrets/subscription_key.txt:/etc/passbolt/subscription_key.txt:ro
    command:
      - /bin/bash
      - -c
      - |
        # Optional LDAP sync task (only if using Passbolt PRO) — configure if needed
        # echo '* * * * * www-data exec /bin/bash -c "source /etc/environment && /usr/share/php/passbolt/bin/cake directory_sync all" >> /var/log/cron.log 2>&1' >> /etc/cron.d/passbolt-pro-server
        /usr/bin/wait-for.sh -t 0 passbolt_db:18001 -- /docker-entrypoint.sh
    ports:
      - "127.0.0.1:11443:8080" # Local binding for reverse proxy access

# ------------------------------------------------
# Docker Secret Definition
# ------------------------------------------------
# The file defined here must exist locally before running
# 'docker compose up'. It will be securely mounted inside
# the container at runtime.
# ------------------------------------------------
secrets:
  db_database:
    file: secrets/credentials/db_database.txt
  db_username:
    file: secrets/credentials/db_username.txt
  db_password:
    file: secrets/credentials/db_password.txt
  server_key_public:
    file: secrets/gpg/serverkey.asc
  server_key_private:
    file: secrets/gpg/serverkey_private.asc

# ------------------------------------------------
# Docker Volume Definition
# ------------------------------------------------
volumes:
  passbolt_jwt_vol:
  passbolt_db_vol:

# ------------------------------------------------
# Docker Network Definition
# ------------------------------------------------
networks:
  default:
    name: passbolt_net