name: emby
services:
    emby:
        container_name: emby
        image: emby/embyserver:latest
        restart: unless-stopped
#        runtime: nvidia
#        network_mode: host
        env_file:
            - emby.env
        volumes:
            - './config:/config'
            - '$storage_path:/mnt/media'
#        devices:
#            - '/dev/dri:/dev/dri'
        labels:
            - "traefik.enable=true"

            - "traefik.tcp.routers.emby_server-https.rule=HostSNI(`emby.domain.com`)"
            - "traefik.tcp.routers.emby_server-https.service=emby_server-https"
            - "traefik.tcp.routers.emby_server-https.tls.passthrough=true"

#            - "traefik.tcp.services.emby_server-https.loadbalancer.server.port=8920"
            - "traefik.tcp.services.emby_server-https.loadbalancer.server.port=8096"
networks:
    default:
        name: emby_net