# ==========================================
# TerminSuite — Traefik Site Configuration
# ==========================================
# This file defines the Traefik router and service for Passbolt.
# All traffic is encrypted with Cloudflare-issued certificates
# and forwarded through the connector container to Passbolt.
# ==========================================

http:
  routers:
    passbolt:
      entryPoints:
        - websecure                             # HTTPS entrypoint
      rule: "Host(`passbolt.domain.com`)"           # Replace with your Cloudflare-proxied domain
      service: passbolt
      tls:
        certresolver: cloudflare                # Use Cloudflare certificate resolver

  services:
    passbolt:
      loadBalancer:
        servers:
          - url: "http://connector:11443"             # Internal SSH tunnel port