# ================================================
# TerminSuite - Traefik Core Configuration
# ================================================
# Description:
#   Main configuration for Traefik reverse proxy,
#   defining providers, logging, entry points,
#   and certificate resolvers.
# ================================================

global:
  sendAnonymousUsage: false

log:
  level: INFO
  format: common

providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    watch: true
    exposedByDefault: false
  file:
    directory: /etc/traefik/conf/
    watch: true

api:
  dashboard: false
  debug: false
  # insecure: true   # Uncomment for local testing only

entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ':443'
    http:
      tls:
        certResolver: cloudflare

certificatesResolvers:
  cloudflare:
    acme:
      email: "admin@diegosr.es"
      storage: "/ssl/acme.json"
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"