name: passbolt
services:
    passbolt_db:
        container_name: passbolt_db
        image: mariadb:latest
        restart: unless-stopped
        env_file:
            - mariadb.env
        secrets:
            - db_database
            - db_username
            - db_password
        volumes:
            - passbolt_db_vol:/var/lib/mysql
            - ./secrets/passbolt.sql:/docker-entrypoint-initdb.d/dump.sql

    passbolt_server:
        container_name: passbolt_server
        # If you want to use PRO version, change latest-ce to latest-pro
        image: passbolt/passbolt:latest-ce-non-root
        restart: unless-stopped
        depends_on:
            - passbolt_db
        env_file:
            - passbolt.env
        secrets:
            - db_database
            - db_username
            - db_password
            - server_key_public
            - server_key_private
            - ssl_cert
            - ssl_key
        volumes:
            - passbolt_jwt_vol:/etc/passbolt/jwt
            # If PRO version is used, you will need the following line
            #- ./secrets/subscription_key.txt:/etc/passbolt/subscription_key.txt:ro
        command:
            - /bin/bash
            - -c
            - |
              # Uncomment line below if you are using ldap sync. Change '* * * * *' to your preferred sync schedule. More info: https://en.wikipedia.org/wiki/Cron
              # echo '* * * * * www-data exec /bin/bash -c "source /etc/environment && /usr/share/php/passbolt/bin/cake directory_sync all" >> /var/log/cron.log 2>&1' >> /etc/cron.d/passbolt-pro-server
              /usr/bin/wait-for.sh -t 0 passbolt_db:3306 -- /docker-entrypoint.sh
        labels:
            - "traefik.enable=true"

            - "traefik.tcp.routers.passbolt_server-https.rule=HostSNI(`passbolt.domain.com`)"
            - "traefik.tcp.routers.passbolt_server-https.service=passbolt_server-https"
            - "traefik.tcp.routers.passbolt_server-https.tls.passthrough=true"

            - "traefik.tcp.services.passbolt_server-https.loadbalancer.server.port=4433"
secrets:
    db_database:
        file: secrets/credentials/db_database.txt
    db_username:
        file: secrets/credentials/db_username.txt
    db_password:
        file: secrets/credentials/db_password.txt
    server_key_public:
        file: secrets/gpg/serverkey.asc
    server_key_private:
        file: secrets/gpg/serverkey_private.asc
    ssl_cert:
        file: ~/ssl/domain.com/fullchain.pem
    ssl_key:
        file: ~/ssl/domani.com/privkey.pem
volumes:
    passbolt_jwt_vol:
    passbolt_db_vol:
networks:
    default:
        name: passbolt_net
