# ================================================
# TerminSuite - Traefik TLS Configuration
# ================================================
# Description:
#   Enforces TLS 1.2+, strict SNI validation,
#   and secure cipher suites for all connections.
# ================================================

tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
      curvePreferences:
        - CurveP521
        - CurveP384
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256