# ================================================
# TerminSuite - Traefik Container Configuration
# ================================================
# Description:
#   This compose file deploys Traefik as the reverse proxy
#   for TerminSuite, managing secure routing and certificates.
#
#   It integrates with Cloudflared (through cloudflared_net)
#   and automatically issues certificates via Cloudflare DNS.
# ================================================

name: traefik

services:
  traefik:
    container_name: traefik
    image: traefik:latest
    restart: unless-stopped
    env_file:
      - traefik.env
    networks:
      - cloudflared_net
      - connector_net
    volumes:
      - /run/user/1001/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/traefik.yaml:ro
      - ./conf/:/etc/traefik/conf
      - ./ssl:/ssl

# ------------------------------------------------
# Docker Network Definition
# ------------------------------------------------
networks:
  cloudflared_net:
    name: cloudflared_net
    external: true
  connector_net:
    name: connector_net
    external: true