name: keycloak
services:
    keycloak_db:
        container_name: keycloak_db
        image: postgres:latest
        restart: unless-stopped
        env_file:
            - postgresql.env
        secrets:
            - db_database
            - db_username
            - db_password
        volumes:
            - keycloak_db_vol:/var/lib/postgresql/data
    keycloak_server:
        container_name: keycloak_server
        image: quay.io/keycloak/keycloak:latest
        restart: unless-stopped
        depends_on:
            - keycloak_db
        env_file:
            - keycloak.env
        secrets:
            - db_username
            - db_password
        volumes:
            - keycloak_data_vol:/opt/keycloak/data
            - ./secrets/realms:/opt/keycloak/data/import
            - ~/ssl/domain.com/fullchain.pem:/opt/keycloak/conf/server.crt.pem
            - ~/ssl/domain.com/privkey.pem:/opt/keycloak/conf/server.key.pem
        command:
#            - start-dev # Uncomment when going to development
#            - build
            - start # Uncomment when going to production
#            - --optimized
            - --import-realm
            - --verbose
        labels:
            - "traefik.enable=true"

            - "traefik.tcp.routers.keycloak_server-https.rule=HostSNI(`keycloak.domain.com`)"
            - "traefik.tcp.routers.keycloak_server-https.service=keycloak_server-https"
            - "traefik.tcp.routers.keycloak_server-https.tls.passthrough=true"

            - "traefik.tcp.services.keycloak_server-https.loadbalancer.server.port=8443"
secrets:
    db_database:
        file: secrets/credentials/db_database.txt
    db_username:
        file: secrets/credentials/db_username.txt
    db_password:
        file: secrets/credentials/db_password.txt
volumes:
  keycloak_db_vol:
      driver: local
  keycloak_data_vol:
networks:
    default:
        name: keycloak_net
